languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Oscillate Labs"
# copyright = "© 2024-2025 Oscillate Labs"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Oscillate Labs"
  # image = "img/author.jpg"
  # headline = ""
  # bio = ""
  links = [
    { github = "https://github.com/OscillateLabsLLC" }
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { x-twitter = "https://twitter.com/your_username" },
  ]
